sudo: false

language: node_js

# latest lts
node_js: node

cache:
  directories:
    - ~/.npm

notifications:
  email: false

install: npm install --no-save

script: npm run validate

after_success: npx semantic-release

branches:
  only: master
