name: Validate Code

on: pull_request

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: install dependencies
        run: npm install --no-save

      - name: lint commits
        run:
          npm run lint:commit -- --from="origin/${{ github.base_ref }}"
          --to="origin/${{github.head_ref }}"

      - name: lint js
        run: npm run lint

      - name: run tests
        run: npm run test
        env:
          CI: true
